apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-app
  description: Python app that displays time - named rhdh-app
  annotations:
    argocd/app-name: rhdh-app
    github.com/project-slug: DaggupatiPavan-1/rhdh-app
    backstage.io/kubernetes-namespace: dev
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=rhdh-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
