site_name: 'rhdh-app'
site_description: 'Main documentation for the rhdh-app'
repo_url: https://github.com/DaggupatiPavan-1/rhdh-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'index.md'

